package intenciones.model;
// Generated 18/12/2018 11:00:59 AM by Hibernate Tools 4.3.1



/**
 * Misas generated by hbm2java
 */
public class Misas  implements java.io.Serializable {


     private Integer id;
     private String misa;

    public Misas() {
    }

    public Misas(String misa) {
       this.misa = misa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMisa() {
        return this.misa;
    }
    
    public void setMisa(String misa) {
        this.misa = misa;
    }




}


