package intenciones.model;
// Generated 18/12/2018 11:00:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rogacion generated by hbm2java
 */
public class Rogacion  implements java.io.Serializable {


     private Integer id;
     private String intencion;
     private String motivo;
     private Date fecha;
     private String misa;

    public Rogacion() {
    }

    public Rogacion(String intencion, String motivo, Date fecha, String misa) {
       this.intencion = intencion;
       this.motivo = motivo;
       this.fecha = fecha;
       this.misa = misa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIntencion() {
        return this.intencion;
    }
    
    public void setIntencion(String intencion) {
        this.intencion = intencion;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMisa() {
        return this.misa;
    }
    
    public void setMisa(String misa) {
        this.misa = misa;
    }




}


