package intenciones.model;
// Generated 18/12/2018 11:00:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sufragio generated by hbm2java
 */
public class Sufragio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String fecharecuerdo;
     private Date fecha;
     private String misa;

    public Sufragio() {
    }

    public Sufragio(String nombre, String fecharecuerdo, Date fecha, String misa) {
       this.nombre = nombre;
       this.fecharecuerdo = fecharecuerdo;
       this.fecha = fecha;
       this.misa = misa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFecharecuerdo() {
        return this.fecharecuerdo;
    }
    
    public void setFecharecuerdo(String fecharecuerdo) {
        this.fecharecuerdo = fecharecuerdo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMisa() {
        return this.misa;
    }
    
    public void setMisa(String misa) {
        this.misa = misa;
    }



}


