package intenciones.model;
// Generated 18/12/2018 11:00:59 AM by Hibernate Tools 4.3.1



/**
 * Tipointencion generated by hbm2java
 */
public class Tipointencion  implements java.io.Serializable {


     private Integer id;
     private String detalle;

    public Tipointencion() {
    }

    public Tipointencion(String detalle) {
       this.detalle = detalle;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


